### ISSUE TITLE
Repeated colored dot in message list

### ISSUE THREAD

**Issue by helmo** [mike-kfed/roundcube-thunderbird_labels#40]
I noticed that the colored dot in the message list is sometimes repeated when you leave the window open for a while.

![selection_050](https://user-images.githubusercontent.com/104120/48068799-16678700-e1d4-11e8-8745-24063194481a.png)

The tag `<span class="tb_label_LABEL2">•</span>` is then repeated.

It also disappears again, seemingly when a new mail arrives. Could it be that it's added every time roundcube checks for new mail in the background?

**Comment by helmo** [comment]
I was just working on a fix in the commit mentioned above but that is not yet fixing the problem.

**Comment by mike-kfed** [comment]
Which roundcube version, roundcube theme and rcmail-thunderbirdlabels version are we talking about here? Also which browser?
I think it is theme larry with the "list only" display?

cannot reproduce with roundcube 1.3.8 and my current master on current Chrome - waited for many refreshes to happen, new mails come in, no bullets added. I need more details please.

**Comment by helmo** [comment]
It's the package from Debian stable (1.2.3+dfsg.1-4+deb9u2) with the master branch of this plugin.

I've seen the issue in both Firefox and Chrome. And with both the larry and the classic skins.

**Comment by mike-kfed** [comment]
I don't have Debian easily accessible, but a git checkout of roundcube-1.2.3 with my plugin also does not show that problem for me... can you please try to use the normal roundcube source package?

**Comment by helmo** [comment]
I did today install the 1.3.8+dfsg.1-2 version which is in the Debian testing repository. I've reverted to the master branch of this plugin. Unfortunately that shows the same problem.

The larry skin: (also note the labels on the right overlapping the sender name)

![selection_064](https://user-images.githubusercontent.com/104120/48646771-12b0dd00-e9ea-11e8-9856-6c9e07efddc2.png)


The classic skin:
![selection_065](https://user-images.githubusercontent.com/104120/48646785-1fcdcc00-e9ea-11e8-931f-56be00976534.png)


After switching to my repeated-colored-dot-2 the issue was gone again.

**Comment by mike-kfed** [comment]
Well this is still not the actual source of roundcube but the debian package. maybe they patched the software somehow? = not what I am testing against. I'll try to see how I can get ahold of that debian stuff. Would be cool if you can check if that behaviour is also true for a source install of roundcube, because if not, this bugreport should go to Debian and not here...

Yeah your hack makes the visual effect of multiple labels disappear, but it's a bandaid that doesn't address the underlying problem (the tag-id missing in the message property). My weekend is kinda packed, so I don't know when I have time to figure out differences that cause that problem. And without seeing the problem I also can't come up with the correct fix...

**Comment by helmo** [comment]
Tried on a different server with PHP 5.6.38, and with the roundcube source directly from git. Both show the extra dots.
What else could be different? I'll sent you credentials to a dev server.

**Comment by mike-kfed** [comment]
thanks for your help tracking this down! Only happened when IMAP server returns a full list of mails and labels on refresh (which seems to be unusual but possible).

**Comment by helmo** [comment]
Thanks, this is better then my pull request.
