### ISSUE TITLE
auto labels with filters?

### ISSUE THREAD

**Issue by luvis** [mike-kfed/roundcube-thunderbird_labels#53]
I'm moving from gmail to roundcube and I've been using filters i gmail for ages adding labels to messages which is super handy. Using sieve filters only creates the option to move messages to a folder or mark as read or flag them, but I can't actually automatically label a message with "to do" or something like that and still leave it in the inbox. Would it be possible, either to use sieve filters variables to auto label messages with thunderbird labels? Or would it be possible to add some kind of filtering directly in the thunderbird-labels settings? Maybe a collab with https://github.com/6ec123321/filters/ ?

For example, this is how I use labels i gmail today for our business.

If to -> support@mailaddress.com ->label "support query"
if to -> billing@mailaddress.com ->label "finances" 

I'm pretty much using it as a ticketing system except without ticket numbers.

In any case, thank you for providing this plugin, it saves me a lot of time.

**Comment by mike-kfed** [comment]
Depending on your SIEVE implementation the `addflag "finances"` command should work for you, see https://wiki2.dovecot.org/Pigeonhole/Sieve/Examples#Flagging_or_Highlighting_your_mail

Issue for arbritary labels support exists see #17 if you want to contribute.

Since this is a SIEVE question and not really related to my project I am closing this issue.
