### ISSUE TITLE
Move default settings to config.inc.php.dist

### ISSUE THREAD

**Issue by buttercookie42** [mike-kfed/roundcube-thunderbird_labels#57]
Would it be possible to follow the apparent convention of providing the default config as `config.inc.php.dist`, so that updating/reinstalling this plugin via composer doesn't overwrite my own config in `config.inc.php`?

**Comment by mike-kfed** [comment]
good idea, thanks. It is now renamed in master and release 1.4.7 - will take some time to be picked up by the plugins repo. Please let me know if it works fine for you

**Comment by buttercookie42** [comment]
Thanks, will check it out.

**Comment by mike-kfed** [comment]
I copied a config.inc.php file in my composer installed plugin dir, after doing composer update or install it removes the file, so your goal of keeping your config is still not reached. I guess this needs playing with some pre and post-install hooks of composer. Since I have no experience with that tool I'd need help to do this (as this needs to be done safely, it's copying renaming files...)

**Comment by buttercookie42** [comment]
Hmm yes, probably related to [this in the plugin installer](https://github.com/roundcube/plugin-installer/blob/98af3c61566b4387aeae76cfa89076a8c39a0ddc/src/Roundcube/Composer/PluginInstaller.php#L60), although the way I'm reading it, it's not supposed to overwrite an already existing config file?

**Comment by mike-kfed** [comment]
okay they only have it on install not on upgrade, when I remove the plugin dir and install it again - it worked for me on master. doing a new release now, 🤞 this is it
