### ISSUE TITLE
Redundant span doubles row height

### ISSUE THREAD

**Issue by moisseev** [mike-kfed/roundcube-thunderbird_labels#66]
For `$config['tb_label_style'] = "thunderbird";` the following `span` elements are not used and just eat vertical space:

![image](https://user-images.githubusercontent.com/2275981/183356873-6fd15d77-ef83-411f-ae95-a5c02fc75300.png)

**Comment by mike-kfed** [comment]
which version of the plugin are you using? On roundcube v1.6.0 and thunderbird_labels v1.4.12 I don't have additional vertical space used in "thunderbird style".

However I'll accept a pull-request that avoids the creation of those spans - if you really need to keep your old roundcube and old theme, because please note as of roundcube 1.6.0 "Larry and Classic are no longer part of the release packages" see their release notes.

**Comment by moisseev** [comment]
Sorry, I didn't mention the version numbers. I have this issue with thunderbird_labels v1.4.12 on roundcube v1.5.3.

If the current plugin version is not supposed to be compatible with earlier roundcube versions then it's fine. It just would be nice if you mentioned requirements in the release notes.

FYI As I understand roundcube 1.6.0 release notes, Larry and Classic are not deprecated, just not included in packages anymore.

**Comment by mike-kfed** [comment]
The plugin is compatible, because it works for you - no need to mention anything in the release notes. You have an aesthetic problem with a certain configuration. You can go ahead and fix that, likely just a CSS based workaround needed I guess?

What I wanted to say with the roundcube 1.6.0 release is, that it's more effort to install the other skins, skins that I don't use and others probably don't either since "elastic" has been out for a long time and is the default skin. Since this is just a side project for me, and not technically broken (e.g. labels not shown at all) I wont invest time into fixing this particular issue. I'll leave it open, maybe somebody has the time to look into it, as I said I'll accept a PR for it.
