### ISSUE TITLE
The plugin doesnt work in Roundcube 1.6.1

### ISSUE THREAD

**Issue by InputOutputZ** [mike-kfed/roundcube-thunderbird_labels#73]
Hi there,

I tested the plugin in RC 1.6.1, it doesn't work. I was wondering if the recent release applies to the fact RC 1.6.1 comes only with elastic skin?

This is the problem that happens when I click on Labels button in message view, in Safari and chrome. The browser throws this error in console and doesn't display the menu.

<img width="1203" alt="Screenshot 2023-03-25 at 17 40 20" src="https://user-images.githubusercontent.com/4721398/227733019-08db4948-1c89-4ea9-99ad-0240a981fcf0.png">

<img width="2560" alt="Screenshot 2023-03-25 at 17 42 15" src="https://user-images.githubusercontent.com/4721398/227733066-a7081681-865b-4859-b3d9-d3e5e7fd2acb.png">

I tried to fix but couldn't and I hope it to be fixed soon.

Looking forward, with thanks.

Zakaria.

**Comment by mike-kfed** [comment]
well given that your traceback shows a problem inside jquery and not in this plugin's code, I take it your roundcube install is somehow broken? For me it works fine in Elastic skin on RC 1.6.1 and most recent plugin version v1.6.1 
If you are having problems in a different legacy skin, you then have a custom install of RC, I am sorry but then you're on your own getting it to work.

**Comment by InputOutputZ** [comment]
Aha, anyways, for those who might have this bug, I changed tb_label_popup:thunderbird_labels.php in line 420, add_footer to add_header and its working just fine. The issue was popup_init in Roundcube ui.js fails registering event listeners on the #tb-label-menu element.

I wonder whats your input? and if such change from long term its ok?

With thanks.

Zakaria.

**Comment by mike-kfed** [comment]
using `add_header()` produces invalid html, because then the divs are inside the `<head>` element. This means I would not accept that as a PR.
Maybe verify that the html generated by your RC install is sane? potentially there is a another plugin messing with the html output and that is how javascript cannot find the element with `id="tb-label-menu"` when `add_footer` is used?

**Comment by mike-kfed** [comment]
Your screenshot shows the DOM tree in the inspector not the HTML source. The browser auto-fixes the broken html hence it looks like it is fine, but that doesn't make the html valid.

Also reading the API docs of Roundcube shows that using `add_footer()` is the right method to use, using `add_header()` is for a different purpose.

**Comment by InputOutputZ** [comment]
Aha, true its appended it to the head tag but the browser fix it. I thought add_header was referencing layout header element but I noticed RC adds the popup menus elements above its buttons while tb labels now append it at the bottom after bundle js if footer.html template was modified, which was the problem. 

Once more, in case anyone come across this issue. For now, this is how I fixed it with customised footer.html, via either making sure bootstrap bundle is appended at the very bottom of footer.html before </body> and after any custom scripts, or using $this->api->add_content with either messagemenu or taskbar container instead of add_footer.

With thanks.

Zakaria.

**Comment by mike-kfed** [comment]
You can look at Roundcube's `program/include/rcmail_output_html.php` in line 2117 is a hilarious code block that injects the footer for elastic templates. You might want to change that and make a PR to RC to not guesstimate where to put stuff. (e.g. make a template variable that is being replaced). Then you can modify the templates in a stable way and not have to change plugin code.

closing because this issue is not happening on vanilla RC.
